server:
  port: 9080
  error:
    include-message: always

logging:
  level:
    org.springframework: INFO
    org.executor: DEBUG

executor:
  simulation:
    run-duration: 5s
    outcome: SUCCEEDED
