server:
  port: 9080

logging:
  level:
    org.springframework: INFO
    org.executor: DEBUG
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always
